import aiohttp import discord from discord.ext import commands from discord import app_commands, Interaction, Embed, ButtonStyle from discord.ui import View, Button GUILD_ID = 1443687099575570544 SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwVjA19y13i6ZoFMq1Yc0y38lx8OdmWmilMgf6DtvGbjbFQsvSqNv6qBcE0r_Inw_u7wg/exec" STATES = ["Overall", "Florida", "California"] DIVISION_ORDER = {"7A": 0, "6A": 1} class StandingsView(View): def __init__(self, user, california, florida): super().__init__(timeout=None) self.user = user self.california = california self.florida = florida self.page = 0 def rank_key(self, t): return ( -t.get("Wins", 0), DIVISION_ORDER.get(t.get("Division"), 9), -t.get("PD", 0), -t.get("PF (Points For)", t.get("PF (Points Scored)", 0)), t["Team"] ) def build_embed(self): state = STATES[self.page] embed = Embed(title=f"🏈 {state} Standings", color=discord.Color.green()) if state == "Overall": teams = self.california + self.florida ranked = sorted(teams, key=self.rank_key)[:32] desc = "
"
            for i, t in enumerate(ranked, 1):
                desc += f"{i:>2}. {t['Team']:<22} {t['Wins']}-{t['Losses']}  PD:{t['PD']}\n"
            desc += "
" embed.description = desc else: teams = self.florida if state == "Florida" else self.california for div in ["7A", "6A"]: filtered = [t for t in teams if t["Division"] == div] ranked = sorted(filtered, key=self.rank_key)[:8] block = f"**{div} Division**\n
"
                for i, t in enumerate(ranked, 1):
                    block += f"{i}. {t['Team']:<22} {t['Wins']}-{t['Losses']}  PD:{t['PD']}\n"
                block += "
" embed.add_field(name="\u200b", value=block, inline=False) embed.set_footer(text=f"Requested by {self.user}") return embed async def interaction_check(self, interaction: Interaction) -> bool: return interaction.user == self.user @discord.ui.button(label="◀", style=ButtonStyle.secondary, custom_id="standings_prev") async def prev_button(self, interaction: Interaction, button: Button): self.page = (self.page - 1) % len(STATES) await interaction.response.edit_message(embed=self.build_embed(), view=self) @discord.ui.button(label="▶", style=ButtonStyle.primary, custom_id="standings_next") async def next_button(self, interaction: Interaction, button: Button): self.page = (self.page + 1) % len(STATES) await interaction.response.edit_message(embed=self.build_embed(), view=self) class Standings(commands.Cog): def __init__(self, bot): self.bot = bot @app_commands.command(name="standings", description="View high school football standings") @app_commands.guilds(discord.Object(id=GUILD_ID)) async def standings(self, interaction: Interaction): await interaction.response.defer() async with aiohttp.ClientSession() as session: try: async with session.get(SCRIPT_URL, timeout=10) as resp: data = await resp.json() california = data["california"] florida = data["florida"] except Exception as e: await interaction.followup.send(f"❌ Could not fetch standings.\n{e}", ephemeral=True) return view = StandingsView(interaction.user, california, florida) await interaction.followup.send(embed=view.build_embed(), view=view) async def setup(bot): await bot.add_cog(Standings(bot))
